apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-argo1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/EwanWCW/Team-5-argo.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: team5

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
